pipeline {
    agent any

    environment {
        ZeroLauncher_CI = '1'

        VERSION_TYPE = 'dev'
        MICROSOFT_AUTH_ID = credentials('microsoft_auth_id')
        CURSEFORGE_API_KEY = credentials('curseforge_api_key')
        ZeroLauncher_SIGNATURE_KEY = credentials('zero_signature_key')
    }

    stages {
        stage('Build') {
            steps {
                sh 'bash ./config/jenkins/config-jenkins.sh'
                sh './gradlew clean makeExecutables makeDeb --stacktrace --no-daemon'
                archiveArtifacts artifacts: 'ZeroLauncher/build/libs/*'
            }
        }
    }
}
